#!/usr/bin/env bash

# Creates a custom Vim indent file disabling indentation of case labels
# in Shell scripts.
# Must be run from ~/.vim (Linux) or ~/vimfiles (Windows) directory.
#
# Latest revision: 2024-12-26
#
# Written and unlicensed by Mikołaj Bartnicki <mikolaj@bartnicki.org>;
# please read LICENSE file for details.

# Exit on first error
set -e

vimRepoUrl="https://github.com/vim/vim"
currentTime=$(date +%s)
cloneDir="vim$currentTime"
localIndentDir="indent"
shellIndentFile="sh.vim"

function CloneVimRepository() {
	git clone $vimRepoUrl $cloneDir
}

function CreateLocalIndentFile() {
	mkdir -p $localIndentDir
	cp $cloneDir/runtime/indent/sh.vim $localIndentDir
}

function RemoveCloneDirectory() {
	rm -rf $cloneDir
}

function ModifyLocalIndentFile() {
	defaultSetting="'case-labels': function('shiftwidth')"
	newSetting="'case-labels': 0"
	sed -i "s/$defaultSetting/$newSetting/g" "$localIndentDir/$shellIndentFile"
}

function Main() {
	CloneVimRepository
	CreateLocalIndentFile
	RemoveCloneDirectory
	ModifyLocalIndentFile
}

Main
